version: '3'
services:
  dev:
    build:
      context: .
      args:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
    volumes:
      - ./:/code
      - ./data:/data
    environment:
      - TERADATA_HOST
      - TERADATA_PORT
      - TERADATA_DATABASE
      - TERADATA_SCHEMA
      - TERADATA_USERNAME
      - TERADATA_PASSWORD
